

CREATE TABLE IF NOT EXISTS users
(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(30)                           NOT NULL,
email VARCHAR(55)                          NOT NULL,
CONSTRAINT pk_user PRIMARY KEY (id)
);